package com.codecool.shop.database;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.*;
import java.util.List;

/**
 * This is a wrapper class which helps the methods containing SQL queries to connect to database
 * and close connection after data handling is ready.
 * <p>
 * It implements the AutoCloseable interface.
 *      Closes this resource, relinquishing any underlying resources.
 *      This method is invoked automatically on objects managed by the
 *      {@code try}-with-resources statement.
 *      @throws Exception if this resource cannot be closed
 *
 * @author  Zsuzsa Petho
 * @version 1.0
 * @since   2018-01-20
 */
public class ConnectionHandler implements AutoCloseable {
    private Connection con;

    private static final Logger logger = LoggerFactory.getLogger(ConnectionHandler.class);

    /**
     * This method set up a Connection to database. It collects data (like path to database,
     * user, password) from Config class to connect to database.
     */
    private void before() {
        try {
            con = DriverManager.getConnection(
                    Config.getDATABASE(),
                    Config.getDB_USER(),
                    Config.getDB_PASSWORD());
        } catch (SQLException e) {
            e.printStackTrace();
            logger.warn("DriverManager.getConnection in ConnectionHandler failed");
        }
        logger.debug("DriverManager.getConnection in ConnectionHandler OK");
    }

    /**
     *This method make a PreparedStatement from a String and a List of TypeCasters. Then execute it.
     * If it fails to execute then it throws an SQLException.
     * @param query
     * @param listOfFieldLabels
     * @throws SQLException if the generated PreparedStatement is not valid
     */
    public void execute(String query, List<TypeCaster> listOfFieldLabels) throws SQLException {
        before();
        PreparedStatement pstm = con.prepareStatement(query);
        pstm = preparedStatementCreator(pstm, listOfFieldLabels);
        pstm.execute();
    }

    /**
     *This method make a PreparedStatement from a String. Then execute it.
     * If it fails to execute then it throws an SQLException.
     * @param query
     * @throws SQLException
     */
    public void execute(String query) throws SQLException {
        before();
        PreparedStatement pstm = con.prepareStatement(query);
        pstm.execute();
    }

    /**
     *This method make a PreparedStatement from a String and a List of TypeCasters. Then execute it
     * and return the ResulSet of the SQL query.
     * If it fails to execute then it throws an SQLException.
     * @param query
     * @param listOfFieldLabels
     * @return ResulSet object generated by the query.
     * @throws SQLException
     */
    public ResultSet process(String query, List<TypeCaster> listOfFieldLabels) throws SQLException {
        before();
        PreparedStatement pstm = con.prepareStatement(query);
        pstm = preparedStatementCreator(pstm, listOfFieldLabels);
        return pstm.executeQuery();
    }

    /**
     *This method make a PreparedStatement from a String. Then execute it and return the ResulSet of
     * the SQL query.
     * If it fails to execute then it throws an SQLException.
     * @param query
     * @return ResulSet object generated by the query.
     * @throws SQLException
     */
    public ResultSet process(String query) throws SQLException {
        before();
        PreparedStatement pstm = con.prepareStatement(query);
        return pstm.executeQuery();
    }

    /**
     *This method construct a full PreparedStatement from a PreparedStatement and a List of TypeCasters.
     * @param pstm
     * @param listOfFieldLabels
     * @return PreparedStatement object construct by the method.
     * @throws SQLException
     */
    private PreparedStatement preparedStatementCreator(PreparedStatement pstm, List<TypeCaster> listOfFieldLabels) throws SQLException {
        for (int i = 0; i < listOfFieldLabels.size(); i++) {
            String content = listOfFieldLabels.get(i).getContent();
            if (listOfFieldLabels.get(i).isNumber()) {
                if (content.contains(".")){
                    pstm.setFloat(i + 1, Float.valueOf(content));
                } else {
                    pstm.setInt(i + 1, Integer.parseInt(content));
                }
            } else {
                pstm.setString(i + 1, content);
            }
        }
        return pstm;
    }

    /**
     * Closes this resource, relinquishing any underlying resources.
     * This method is invoked automatically on objects managed by the
     * {@code try}-with-resources statement.
     */
    @Override
    public void close() {
        try {
            con.close();
            logger.debug("Connection in ConnectionHandler successfully closed");
        } catch (SQLException e) {
            e.printStackTrace();
            logger.warn("Close connection in ConnectionHandler failed");
        }
    }

}
